import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "/styles/Home.module.css";
import Hero from "../features/Home/Hero";
import BestSeller from "../features/Home/BestSeller";
import NewsLetter from "../features/Home/NewsLetter";
import Featured from "../features/Home/Featured";

//------------- for custom layout
// import { ReactElement } from "react";
// import GlobalLayout from "../components/Layouts/GlobalLayout";

const inter = Inter({ subsets: ["latin"] });

/**
 *
 * @returns {JSX.Element}:The JSX.Element for the Home page
 */

export default function Home() {
  return (
    <>
      <Head>
        <title>Luxify | shop your attitute</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Hero />
        <BestSeller />
        <NewsLetter />
        <Featured />
      </main>
    </>
  );
}

//------------- for custom layout
// Home.getLayout = function getLayout(page: ReactElement) {
//   return <GlobalLayout>{page}</GlobalLayout>;
// };
